INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Software Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Manager - Sales', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Project Director', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Business Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Technical Lead', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Lead Database Administrator', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Technical Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Software Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Lead - Quality Engineering', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Manager - Quality Engineering', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Consultant', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - Engineering', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'UI Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Manager - Client Partner', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Quality Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Business Analyst', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Manager - Business Development', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Business Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Program Manager', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - Client Partner', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Manager - Quality Engineering', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Manager - Sales', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - Sales', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Technical Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'UI Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Lead Quality Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Technical Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Business Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Project Manager', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Data Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Manager - HR', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Executive - Finance', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Quality Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Executive - Business Development', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Manager - Finance', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Principal Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Data Analyst', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Executive - HR', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Lead Technical Writer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Lead Systems Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Systems Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Systems Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Project Trainee', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Encompass Administrator', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Systems Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - HR', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Manager - Encompass', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Encompass Developer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'UX Designer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Lead Technical Writer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Engineering Manager', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Encompass Administrator', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Executive - HR', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Sales', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Systems Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Vice President - Sales', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - RMG', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Analytics', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Manager - Marketing', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Manager - Marketing', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Manager - RMG', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - HR', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Lead Systems Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - IS', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Executive - Marketing', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Global Services', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - Finance', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Chief Information Officer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Chief Financial Officer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Project Manager', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Program Manager', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Executive Vice President', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate UI Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Vice President - Delivery', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Lead Data Scientist', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Data Scientist', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. UI Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Technology & Architecture', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Hortonworks Administrator', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Executive - Business Development', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Data Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'UI Lead', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Vice President - Consumer Lending', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Business Analyst', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Lead Business Analyst', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Project Manager', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Software Quality Assurance Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate UX Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Deputy Manager - HR', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sales & Marketing Ops Manager', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Manager - HR', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'UX Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'UX Lead', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Director - Business Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Intern', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Business Solutions', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Lead - Hortonworks Administrator', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Director - Product', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Vice President - Delivery', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Director - IS', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - Business Analysis', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Client Partner', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Manager - HR', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Vice President - Sales', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Network Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Technical Recruiter', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Vice President - EBusiness', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Chief of Staff', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Information Security Administrator', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Director - Technology', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Director - Project Management', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Business Development', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Vice President - Sales', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - Technology & Architecture', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Project Management', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Engineering Manager', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Lead Technical Recruiter', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Technical Manager', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Information Security Administrator', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Process and Quality Analyst', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Manager - SEPG', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Program Management', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Chief Delivery Officer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - IS', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Manager - Facilities', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Chief Executive Officer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Chief Revenue Officer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Lead Database Administrator', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Facilities', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - Consumer Lending', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Lead Network Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Vice President - Artificial Intelligence', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Manager - Finance', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Software Quality Assurance Engineer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Technical Analyst', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Manager - Quality Engineering', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Manager - Information Security', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Manager - Business Development', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Manager - Finance', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - Program Management', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Deputy Manager - Facilities', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Vice President - Quality Engineering', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Data Scientist', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Market Research Executive - Inside Sales', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Lead Data Scientist', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Database Administrator', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - UI', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Vice President - Analytics', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Immigration Counsel', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Vice President & Global Head- HR', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Database Architect', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - Machine Learning Products', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Associate Vice President - Project Management', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Vice President - Delivery', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Executive - Marketing', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Director - EBusiness', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Client Executive', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Consumer Lending', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Vice President - Technology & Architecture', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Director - Finance', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Executive - Finance', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Executive - Facilities', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Market Research Executive - Inside Sales', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Deputy Manager - Business Development', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Deputy Manager - Finance', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Sr. Manager - Marketing', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Executive - PMO', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Interpreter', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Vice President - Digital', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Deputy Manager - PMO', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Chief Technology Officer', now(), null, 1, '1');
INSERT INTO cranium.title ( title_id, name, created_on, modified_on, created_by, is_active ) VALUES ( nextval('cranium.title_id_sequence'), 'Manager - PMO', now(), null, 1, '1');
