

/* Dummy Users - Employee Table*/
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Sr. Program Manager'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'Dev'), 'MAN-1', 'MAN-1', 'man-1', 'man1@mailinator.com', 'man-1', '2010-10-21', true, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Sr. Program Manager'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'Dev'), 'MAN-2', 'MAN-2', 'man-2', 'man2@mailinator.com', 'man-2', '2010-10-21', true, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Sr. Program Manager'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'Dev'), 'MAN-3', 'MAN-3', 'man-3', 'man3@mailinator.com', 'man-3', '2010-10-21', true, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Sr. Program Manager'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'Dev'), 'MAN-4', 'MAN-4', 'man-4', 'man4@mailinator.com', 'man-4', '2010-10-21', true, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Sr. Program Manager'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'Dev'), 'MAN-5', 'MAN-5', 'man-5', 'man1@mailinator.com', 'man-5', '2010-10-21', true, now(), 1, true);

insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Vice President - Digital'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'Dev'), 'GDM-1', 'GDM-1', 'gdm-1', 'gdm1@mailinator.com', 'gdm-1', '2010-10-21', false, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Vice President - Digital'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'Dev'), 'GDM-2', 'GDM-2', 'gdm-2', 'gdm2@mailinator.com', 'gdm-2', '2010-10-21', false, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Vice President - Digital'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'Dev'), 'GDM-3', 'GDM-3', 'gdm-3', 'gdm3@mailinator.com', 'gdm-3', '2010-10-21', false, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Vice President - Digital'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'Dev'), 'GDM-4', 'GDM-4', 'gdm-4', 'gdm4@mailinator.com', 'gdm-4', '2010-10-21', false, now(), 1, true);

insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Deputy Manager - PMO'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'PMO'), 'PMO-1', 'PMO-1', 'pmo-1', 'pmo1@mailinator.com', 'pmo-1', '2010-10-21', false, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Deputy Manager - PMO'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'PMO'), 'PMO-2', 'PMO-2', 'pmo-2', 'pmo2@mailinator.com', 'pmo-2', '2010-10-21', false, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Deputy Manager - PMO'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'PMO'), 'PMO-3', 'PMO-3', 'pmo-3', 'pmo1@mailinator.com', 'pmo-3', '2010-10-21', false, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Deputy Manager - PMO'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'PMO'), 'PMO-4', 'PMO-4', 'pmo-4', 'pmo2@mailinator.com', 'pmo-4', '2010-10-21', false, now(), 1, true);

insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Director - RMG'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Support'), (select division_id from cranium.division where name = 'Resource Management Group'), (select department_id from cranium.department where name = 'Resource Management Group'), 'RMG-1', 'RMG-1', 'rmg-1', 'rmg1@mailinator.com', 'rmg-1', '2010-10-21', false, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Director - RMG'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Support'), (select division_id from cranium.division where name = 'Resource Management Group'), (select department_id from cranium.department where name = 'Resource Management Group'), 'RMG-2', 'RMG-2', 'rmg-2', 'rmg2@mailinator.com', 'rmg-2', '2010-10-21', false, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Director - RMG'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Support'), (select division_id from cranium.division where name = 'Resource Management Group'), (select department_id from cranium.department where name = 'Resource Management Group'), 'RMG-3', 'RMG-3', 'rmg-3', 'rmg3@mailinator.com', 'rmg-3', '2010-10-21', false, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Director - RMG'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Support'), (select division_id from cranium.division where name = 'Resource Management Group'), (select department_id from cranium.department where name = 'Resource Management Group'), 'RMG-4', 'RMG-4', 'rmg-4', 'rmg4@mailinator.com', 'rmg-4', '2010-10-21', false, now(), 1, true);

insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Sr. Program Manager'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'SEPG'), 'SA-1', 'SA-1', 'sa-1', 'sa1@mailinator.com', 'sa-1', '2010-10-21', false, now(), 1, true);
insert into cranium.employee(employee_id, title_id, location_id, business_unit_id, division_id, department_id, first_name, last_name, emp_code, email, login_id, date_of_joining, is_manager, created_on, created_by, is_active) values(nextval('cranium.employee_id_sequence'), (select title_id from cranium.title where name = 'Sr. Program Manager'), (select location_id from cranium.location where name = 'Bangalore'), (select business_unit_id from cranium.business_unit where name = 'Delivery'), (select division_id from cranium.division where name = 'Delivery'), (select department_id from cranium.department where name = 'SEPG'), 'SA-2', 'SA-2', 'sa-2', 'sa2@mailinator.com', 'sa-2', '2010-10-21', false, now(), 1, true);


/* Dummy Users - Employee Roles */
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'man-1'), (select role_id from cranium.role where name = 'MANAGER'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'man-2'), (select role_id from cranium.role where name = 'MANAGER'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'man-3'), (select role_id from cranium.role where name = 'MANAGER'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'man-4'), (select role_id from cranium.role where name = 'MANAGER'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'man-5'), (select role_id from cranium.role where name = 'MANAGER'), now(), 1, true);

INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'gdm-1'), (select role_id from cranium.role where name = 'GDM'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'gdm-2'), (select role_id from cranium.role where name = 'GDM'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'gdm-3'), (select role_id from cranium.role where name = 'GDM'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'gdm-4'), (select role_id from cranium.role where name = 'GDM'), now(), 1, true);

INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'pmo-1'), (select role_id from cranium.role where name = 'PMO'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'pmo-2'), (select role_id from cranium.role where name = 'PMO'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'pmo-3'), (select role_id from cranium.role where name = 'PMO'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'pmo-4'), (select role_id from cranium.role where name = 'PMO'), now(), 1, true);

INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'rmg-1'), (select role_id from cranium.role where name = 'RMG'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'rmg-2'), (select role_id from cranium.role where name = 'RMG'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'rmg-3'), (select role_id from cranium.role where name = 'RMG'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'rmg-4'), (select role_id from cranium.role where name = 'RMG'), now(), 1, true);

INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'sa-1'), (select role_id from cranium.role where name = 'SUPER_ADMIN'), now(), 1, true);
INSERT INTO cranium.employee_roles(employee_roles_id, employee_id, role_id, created_on, created_by, is_active) VALUES (nextval('cranium.employee_roles_id_sequence'), (select employee_id from cranium.employee where emp_code = 'sa-2'), (select role_id from cranium.role where name = 'SUPER_ADMIN'), now(), 1, true);

